[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
via_ir = true                # Enable IR-based code generation
optimizer = true             # Enable the optimizer
optimizer_runs = 200         

# If you need additional optimizer settings:
[profile.default.optimizer_details]
yul = true                   # Enable Yul optimizer